/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dbxfkctwzgzrxlmcytnq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRieGZrY3R3emd6cnhsbWN5dG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5Njc2ODIsImV4cCI6MjA4NTU0MzY4Mn0.e-infhCNhc3ajg-SCoFClOvtgKKnXWiV4mMHjBJYnCI"